spring.application.name=urlshortener
app.base-url=http://localhost:8080
app.machine-id=${MACHINE_ID:1}

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=200ms
spring.data.redis.lettuce.pool.max-active=16